version: '2.1'
services:
  icecast:
    image: threesquared/icecast:latest
    container_name: icecast
    ports:
      - 8000:8000
    volumes:
      - "/path/to/config:/icecast"
  liquidsoap:
    image: phasecorex/liquidsoap:latest
    container_name: liquidsoap
    command: /liquidsoap/config.liq
    volumes:
      - "/path/to/config:/liquidsoap"
      - "/path/to/music:/music"
  radio:
    build: ./
